"""
weapon_damage_cache.py - O(1) lookup for pre-computed weapon expected damage.

Architecture (Option B — per-episode cache):
1. At startup: load weapon_damage_table.json into nested dict (off_key → def_key → dmg)
2. At unit init: stamp _wdc_off_key on each weapon dict, _wdc_def_key on each unit dict
3. At episode reset: build best_weapon_cache for all (attacker_id, is_ranged, target_id) pairs
4. Hot path: single dict lookup with integer keys → O(1)

Generated by: scripts/weapon_damage_builder.py
Loaded by: engine/w40k_core.py at game init
Used by: engine/observation_builder.py
"""

import json
from pathlib import Path
from typing import Dict, Any, Tuple, Optional, List

from engine.combat_utils import expected_dice_value
from shared.data_validation import require_key

NestedTable = Dict[Tuple, Dict[Tuple, float]]
BestWeaponCache = Dict[Tuple, Tuple[int, float]]

_GLOBAL_TABLE: Optional[NestedTable] = None
_TABLE_PATH = Path(__file__).parent.parent / "config" / "weapon_damage_table.json"


def load_weapon_damage_table(path: Optional[Path] = None) -> NestedTable:
    """
    Load pre-computed weapon damage table from JSON into nested dict.

    Returns nested dict: table[off_key][def_key] = expected_damage.
    """
    global _GLOBAL_TABLE
    if _GLOBAL_TABLE is not None:
        return _GLOBAL_TABLE

    table_path = path or _TABLE_PATH
    if not table_path.exists():
        raise FileNotFoundError(
            f"Weapon damage table not found: {table_path}. "
            "Run: python3 scripts/weapon_damage_builder.py"
        )

    with open(table_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if data.get("version") != 1:
        raise ValueError(
            f"Unsupported weapon_damage_table version: {data.get('version')}"
        )

    table: NestedTable = {}
    for off_list, def_list, dmg in data["entries"]:
        off_key = (int(off_list[0]), int(off_list[1]),
                   float(off_list[2]), float(off_list[3]), int(off_list[4]))
        def_key = (int(def_list[0]), int(def_list[1]), int(def_list[2]))
        if off_key not in table:
            table[off_key] = {}
        table[off_key][def_key] = float(dmg)

    _GLOBAL_TABLE = table
    return table


def stamp_weapon_keys(unit: Dict[str, Any]) -> None:
    """
    Pre-compute and store _wdc_off_key on each weapon, _wdc_def_key on unit.

    Called once per unit at game init. Eliminates all require_key/expected_dice_value
    calls from the hot path.
    """
    unit["_wdc_def_key"] = (
        int(unit["T"]),
        int(unit.get("ARMOR_SAVE", 7)),
        int(unit.get("INVUL_SAVE", 7)),
    )
    for weapon in require_key(unit, "RNG_WEAPONS"):
        weapon["_wdc_off_key"] = (
            int(weapon["ATK"]),
            int(weapon["STR"]),
            expected_dice_value(weapon["NB"], "stamp_nb"),
            expected_dice_value(weapon["DMG"], "stamp_dmg"),
            int(weapon["AP"]),
        )
    for weapon in require_key(unit, "CC_WEAPONS"):
        weapon["_wdc_off_key"] = (
            int(weapon["ATK"]),
            int(weapon["STR"]),
            expected_dice_value(weapon["NB"], "stamp_nb"),
            expected_dice_value(weapon["DMG"], "stamp_dmg"),
            int(weapon["AP"]),
        )


def build_best_weapon_cache(
    units: List[Dict[str, Any]],
    table: NestedTable,
    units_cache: Dict[str, Any],
) -> BestWeaponCache:
    """
    Pre-compute best weapon (idx, expected_damage) for every alive (attacker, target) pair.

    Called once per episode reset. Result stored in game_state["_best_weapon_cache"].

    Key: (attacker_id_str, is_ranged_int, target_id_str)
    Value: (best_weapon_idx, best_expected_damage)

    is_ranged_int: 1 for ranged, 0 for melee (int for fast hashing).
    """
    cache: BestWeaponCache = {}

    alive_units = [u for u in units if str(u["id"]) in units_cache]

    for attacker in alive_units:
        att_id = str(attacker["id"])
        att_player = attacker["player"]

        for target in alive_units:
            tgt_id = str(target["id"])
            if target["player"] == att_player:
                continue

            def_key = target["_wdc_def_key"]

            for is_ranged_int, weapons_key in ((1, "RNG_WEAPONS"), (0, "CC_WEAPONS")):
                weapons = require_key(attacker, weapons_key)
                best_idx = -1
                best_dmg = 0.0

                for idx, weapon in enumerate(weapons):
                    off_key = weapon["_wdc_off_key"]
                    off_subtable = table.get(off_key)
                    if off_subtable is None:
                        continue
                    exp_dmg = off_subtable.get(def_key, 0.0)
                    if exp_dmg > best_dmg:
                        best_dmg = exp_dmg
                        best_idx = idx

                cache[(att_id, is_ranged_int, tgt_id)] = (best_idx, best_dmg)

    return cache


def lookup_best_weapon(
    cache: BestWeaponCache,
    attacker_id: str,
    target_id: str,
    is_ranged: bool,
) -> Tuple[int, float]:
    """
    O(1) lookup: best weapon index and expected damage for attacker vs target.

    Returns (-1, 0.0) if pair not in cache (unit dead or same player).
    """
    entry = cache.get((attacker_id, 1 if is_ranged else 0, target_id))
    if entry is None:
        return (-1, 0.0)
    return entry
