"""
weapon_damage_cache.py - O(1) lookup for pre-computed weapon expected damage.

Architecture (Option B — per-episode cache):
1. At startup: load weapon_damage_table.json into nested dict (off_key → def_key → dmg)
2. At unit init: stamp _wdc_off_key on each weapon dict
3. At episode reset: resoudre la sous-table OFFENSIVE de chaque arme de chaque figurine
4. Hot path: cle DEFENSIVE EFFECTIVE calculee a la LECTURE, puis un lookup par arme

⚠️ LE COTE DEFENSIF NE SE PRE-CALCULE PAS. Il l a ete jusqu au 2026-09-10 : `stamp_weapon_keys`
posait un `_wdc_def_key` a l initialisation des unites, et `build_best_weapon_cache` le figeait
au reset. Aucun effet s activant EN COURS DE PARTIE ne pouvait donc etre vu — mesure sur
{5 Boyz + BannerNob attache} : cle figee (5, 5, 7) alors que la resolution joue une invulnerable
5+ des le tour 1 (`invul_save_override`, 19.04) et une T6 sous Waaagh! (19.02). Les bots
surestimaient de 25,0 % ce qu ils infligent a cette escouade.

Generated by: scripts/weapon_damage_builder.py
Loaded by: engine/w40k_core.py at game init
Used by: engine/observation_builder.py
"""

import json
from pathlib import Path
from typing import Dict, Any, Tuple, Optional, List

from engine.combat_utils import expected_dice_value
from shared.data_validation import require_key

NestedTable = Dict[Tuple, Dict[Tuple, float]]
#: Sous-tables offensives d une figurine pour un mode d attaque, dans l ordre de ses armes.
#: `None` = profil d arme absent de la table (aucun degat possible a resoudre).
WeaponSubtables = Tuple[Optional[Dict[Tuple, float]], ...]
BestWeaponCache = Dict[Tuple[str, int], WeaponSubtables]

_GLOBAL_TABLE: Optional[NestedTable] = None
_TABLE_PATH = Path(__file__).parent.parent / "config" / "weapon_damage_table.json"


def load_weapon_damage_table(path: Optional[Path] = None) -> NestedTable:
    """
    Load pre-computed weapon damage table from JSON into nested dict.

    Returns nested dict: table[off_key][def_key] = expected_damage.
    """
    global _GLOBAL_TABLE
    if _GLOBAL_TABLE is not None:
        return _GLOBAL_TABLE

    table_path = path or _TABLE_PATH
    if not table_path.exists():
        raise FileNotFoundError(
            f"Weapon damage table not found: {table_path}. "
            "Run: python3 scripts/weapon_damage_builder.py"
        )

    with open(table_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if data.get("version") != 1:
        raise ValueError(
            f"Unsupported weapon_damage_table version: {data.get('version')}"
        )

    table: NestedTable = {}
    for off_list, def_list, dmg in data["entries"]:
        off_key = (int(off_list[0]), int(off_list[1]),
                   float(off_list[2]), float(off_list[3]), int(off_list[4]))
        def_key = (int(def_list[0]), int(def_list[1]), int(def_list[2]))
        if off_key not in table:
            table[off_key] = {}
        table[off_key][def_key] = float(dmg)

    _GLOBAL_TABLE = table
    return table


def weapon_off_key(weapon: Dict[str, Any]) -> Tuple:
    """Cle offensive d'un profil d'arme, telle que la table l'indexe.

    SOURCE UNIQUE de cette cle. Elle etait construite a l'identique en trois endroits de
    `stamp_weapon_keys` ; `build_best_weapon_cache` en a maintenant besoin pour les armes des
    FIGURINES, qui ne passent pas par le tamponnage (cf. sa docstring). Une quatrieme copie
    aurait diverge de la table au premier champ ajoute.
    """
    return (
        int(weapon["ATK"]),
        int(weapon["STR"]),
        expected_dice_value(weapon["NB"], "stamp_nb"),
        expected_dice_value(weapon["DMG"], "stamp_dmg"),
        int(weapon["AP"]),
    )


def stamp_weapon_keys(unit: Dict[str, Any]) -> None:
    """
    Pre-compute and store _wdc_off_key on each weapon.

    Called once per unit at game init. Eliminates all require_key/expected_dice_value
    calls from the hot path.

    AUCUN `_wdc_def_key` : la cle DEFENSIVE ne se tamponne pas. Elle l etait ici jusqu au
    2026-09-10, et c est ce qui rendait les invulnerables conferees en cours de partie
    invisibles a tous les bots (cf. l en-tete du module). Elle est desormais calculee a la
    LECTURE par `effective_defensive_profile`.
    """
    for weapon in require_key(unit, "RNG_WEAPONS"):
        weapon["_wdc_off_key"] = weapon_off_key(weapon)
    for weapon in require_key(unit, "CC_WEAPONS"):
        weapon["_wdc_off_key"] = weapon_off_key(weapon)


def build_best_weapon_cache(
    units: List[Dict[str, Any]],
    table: NestedTable,
    units_cache: Dict[str, Any],
    models_cache: Dict[str, Any],
    squad_models: Dict[str, Any],
) -> BestWeaponCache:
    """Sous-tables offensives de chaque arme de chaque FIGURINE vivante, par mode d attaque.

    Called once per episode reset. Result stored in game_state["_best_weapon_cache"].

    Key: (attacker_MODEL_id_str, is_ranged_int)
    Value: une sous-table par arme de la figurine, dans l ordre de sa liste d armes.

    is_ranged_int: 1 for ranged, 0 for melee (int for fast hashing).

    ⚠️ PAS DE DIMENSION CIBLE, ET C EST LE POINT. Ce cache indexait aussi la CIBLE et rendait
    directement (meilleure arme, degat) — donc une valeur FIGEE AU RESET pour le cote defensif.
    Un effet qui s active en cours de partie (Waaagh! 08.04, `invul_save_override` 19.04) ou une
    T de bodyguard qui change avec les pertes (19.02) etaient structurellement invisibles.
    Mesure du 2026-09-10 sur {5 Boyz + BannerNob attache} : cle defensive figee a (5, 5, 7)
    alors que la resolution joue (5, 5, 5), soit 0,37037 degat espere annonce contre 0,29630
    reel — 25,0 % de surestimation, sur TOUTES les decisions de tous les bots.
    La cle defensive est desormais posee par `squad_expected_damage` A LA LECTURE, via
    `effective_defensive_profile` (les MEMES oracles que la resolution).

    ⚠️ PAR FIGURINE, ET C EST L AUTRE POINT. Ce cache etait indexe par ESCOUADE et lisait
    `unit["RNG_WEAPONS"]` / `unit["CC_WEAPONS"]`, qui ne portent QUE le profil du soldat de
    base — pas l'union des armes de l'escouade. Sergents, armes speciales et personnages
    attaches y etaient donc invisibles. Mesure du 2026-08-12 sur `scenario_bot-01`, en
    comparant a la vraie somme par figurine : **50 paires (attaquant, cible, phase) sur 90
    etaient fausses, d'un facteur 0,50 en mediane et jusqu'a 0,18** — une escouade menee par
    un personnage passait pour cinq fois moins dangereuse qu'elle ne l'est. Seules les deux
    escouades HOMOGENES du scenario tombaient juste.
    Le moteur, lui, resout toujours par figurine (`engine/utils/weapon_helpers.py` : profils
    « portes par une unite OU une figurine »), donc l'estimation mentait sur le combat reel.

    Les armes des figurines ne sont PAS tamponnees (`stamp_weapon_keys` ne voit que les
    objets `unit`) : leur cle est calculee ici par `weapon_off_key`, la meme fonction. C'est
    une fois par episode, sur quelques dizaines de profils — mesurable, mais sans commune
    mesure avec le cout d'un second tamponnage a maintenir en phase avec `models_cache`,
    qui est reconstruit en cours de partie. Supprimer la dimension CIBLE a d ailleurs divise
    ce cout par le nombre d'escouades ennemies.
    """
    cache: BestWeaponCache = {}

    for attacker in units:
        att_squad_id = str(attacker["id"])
        if att_squad_id not in units_cache:
            continue
        # Les ids de `squad_models` PRESENTS dans `models_cache` : le patron unique du moteur
        # pour « les figurines vivantes de cette escouade » (cf. `select_eligible_models`).
        model_ids = [
            mid for mid in require_key(squad_models, att_squad_id) if mid in models_cache
        ]
        for model_id in model_ids:
            model = models_cache[model_id]
            for is_ranged_int, weapons_key in ((1, "RNG_WEAPONS"), (0, "CC_WEAPONS")):
                weapons = require_key(model, weapons_key)
                cache[(model_id, is_ranged_int)] = tuple(
                    table.get(weapon_off_key(w)) for w in weapons
                )

    return cache


def lookup_best_weapon(
    cache: BestWeaponCache,
    attacker_model_id: str,
    def_key: Tuple[int, int, int],
    is_ranged: bool,
) -> Tuple[int, float]:
    """Meilleure arme (index, degat espere) d UNE FIGURINE contre un profil defensif donne.

    `def_key` est la cle (T, Sv, InSv) EFFECTIVE de la cible, calculee par l appelant a cet
    instant precis : c est elle qui rend l estimation sensible aux effets en cours de partie.

    ⚠️ Le premier terme de la cle du cache est un id de FIGURINE (`models_cache`), pas un id
    d'escouade : passer un id d'escouade rend systematiquement (-1, 0.0), donc « inoffensif ».
    C'est `squad_expected_damage` qui somme sur les figurines vivantes.

    Une entree absente POUR CE PROFIL DEFENSIF vaut zero degat, et c est un RESULTAT : la table
    n ecrit pas les entrees nulles (cf. `weapon_damage_builder`), donc « absente » y veut dire
    « cette arme ne peut pas blesser cette cible ».

    ⚠️ Un PROFIL D ARME absent de la table (`off_subtable is None`) est une TOUT AUTRE chose, et
    il est traite comme zero par defaut de mieux — c est un trou de DONNEE, pas un resultat.
    `scripts/weapon_damage_builder.py` ne balaie que `spaceMarine, tyranid, aeldari,
    adeptusCustodes, chaos` : mesure du 2026-09-10, **18 des 21 armes de l armurerie `ork` sont
    absentes de la table**, dont `shoota` et `slugga`. Consequence mesuree sur 5 Boyz contre 5
    Intercessors : `squad_expected_damage` rend **0,0 au tir** (2,5 en melee, ou `choppa_a3`
    coincide par hasard avec un profil deja construit) — tous les bots tiennent une escouade
    orke pour incapable de tirer. Defaut ANTERIEUR a la correction du 2026-09-10 et non traite
    ici : le corriger exige de regenerer `config/weapon_damage_table.json`.

    Returns (-1, 0.0) if the model is not in the cache (dead, or no weapon of that kind).
    """
    subtables = cache.get((attacker_model_id, 1 if is_ranged else 0))
    if subtables is None:
        return (-1, 0.0)
    best_idx = -1
    best_dmg = 0.0
    for idx, off_subtable in enumerate(subtables):
        if off_subtable is None:
            continue
        exp_dmg = off_subtable.get(def_key, 0.0)
        if exp_dmg > best_dmg:
            best_dmg = exp_dmg
            best_idx = idx
    return (best_idx, best_dmg)


def squad_expected_damage(
    game_state: Dict[str, Any],
    attacker_id: str,
    target_id: str,
    is_ranged: bool,
) -> float:
    """Degats esperes d une ACTIVATION d escouade sur une autre : SOMME sur les figurines vivantes.

    SOURCE UNIQUE des degats esperes du depot, et SEUL consommateur vivant de
    `_best_weapon_cache` : les bots d evaluation (`ai/bot_doctrines.py`) passent tous par ici.
    L'observation de l'agent NE la lit pas — verifie le 2026-08-12 en instrumentant une partie
    complete : son ancien lecteur (`ObservationBuilder._target_priority_score`) n'avait aucun
    appelant et a ete supprime, tout comme les deux aides qu'il tirait derriere lui.

    LA CIBLE EST LUE MAINTENANT, ET C EST LA CORRECTION DU 2026-09-10. Le profil defensif vient
    de `effective_defensive_profile` — les MEMES oracles que la resolution (19.02 pour la T,
    `effective_invul_save` pour l invulnerable). Le cache, lui, ne porte plus que le cote
    OFFENSIF, qui est bien fixe pour l episode. Avant, la cle defensive etait figee au reset :
    une invulnerable conferee par une regle d unite ou par le Waaagh! n existait pour aucun bot.

    CHAQUE FIGURINE TIRE AVEC SON ARME, ET C'EST LA CORRECTION DU 2026-08-12. La version
    precedente prenait la meilleure arme de l'ESCOUADE et la multipliait par l'effectif — or le
    profil d'armes porte par l'objet `unit` n'est que celui du soldat de base, donc sergents,
    armes speciales et personnages attaches ne comptaient pas, et les figurines de base
    comptaient a leur place. Mesure sur `scenario_bot-01` : 50 paires sur 90 fausses, mediane
    0,50x la vraie valeur, pire cas 0,18x (0,78 annonce contre 4,23 reels en melee). Le detail
    du defaut et la forme du cache sont dans `build_best_weapon_cache`.

    POURQUOI CETTE FONCTION EXISTE — les bots tranchaient toutes leurs decisions (menace, choix
    de cible, « tuable ce tour », « charger ou pas ») sur `max(NB x DMG)`, qui ignore le jet pour
    toucher, la Force contre l'Endurance, l'AP contre la sauvegarde, les figurines et la portee.
    Mesure du 2026-08-12 : sur les rosters holdout 500 pts, **17 profils sur 23** passaient pour
    de la melee sous ce proxy, Intercessor compris (fusil a 24 pouces contre couteau) — c'est le
    test qui decide de charger, donc les bots envoyaient leurs tireurs au contact.

    ⚠️ AUCUN REPLI. Un cache absent, une escouade attaquante inconnue de `squad_models` ou une
    CIBLE sans figurine vivante sont des divergences d invariant : elles levent. Rendre 0.0
    ferait passer une escouade inconnue pour une escouade inoffensive, et un bot choisirait sa
    cible sur cette invention. Tous les appelants du depot n interrogent que des ennemis VIVANTS
    (`_living_enemies`, `require_unit_from_cache`), donc la levee de la cible morte ne se
    declenche que sur un vrai desynchronisme.
    Une FIGURINE ATTAQUANTE hors cache, en revanche, ne leve pas : le cache est bati au reset et
    `models_cache` perd ses morts en cours de partie, donc « absent » y veut dire « mort », ce
    que la boucle ecarte deja. C'est la seule asymetrie, et elle est voulue.
    """
    cache = game_state.get("_best_weapon_cache")  # get allowed : l'absence leve juste en dessous
    if cache is None:
        raise RuntimeError(
            "squad_expected_damage exige game_state['_best_weapon_cache'], construit au reset "
            "par W40KEngine ; sans lui, aucune estimation de degats n'est possible."
        )
    models_cache = require_key(game_state, "models_cache")
    squad_models = require_key(game_state, "squad_models")
    att_id = str(attacker_id)
    if att_id not in squad_models:
        raise KeyError(
            f"squad_expected_damage: escouade attaquante {att_id} absente de squad_models."
        )
    # Import paresseux : `shared_utils` tire tout le moteur, et ce module est importe par
    # `w40k_core` avant lui.
    from engine.phase_handlers.shared_utils import effective_defensive_profile

    def_key = effective_defensive_profile(game_state, str(target_id))
    # Les ids PRESENTS dans `models_cache` : patron unique du moteur pour « vivantes »
    # (cf. `shared_utils.select_eligible_models`). Zero figurine vivante = zero degat, ce qui
    # est le RESULTAT et non un repli.
    return sum(
        lookup_best_weapon(cache, mid, def_key, is_ranged)[1]
        for mid in squad_models[att_id]
        if mid in models_cache
    )
